MVCTut/Controllers/AppIndexesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCTut.Models;

namespace MVCTut.Controllers
{
    public class AppIndexesController : Controller
    {
        private AmendmentIDBContext db = new AmendmentIDBContext();

        // GET: AppIndexes
        public async Task<ActionResult> Index()
        {
            return View(await db.AppIndexes.ToListAsync());
        }

        // GET: AppIndexes/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AppIndex appIndex = await db.AppIndexes.FindAsync(id);
            if (appIndex == null)
            {
                return HttpNotFound();
            }
            return View(appIndex);
        }

        // GET: AppIndexes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AppIndexes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,AppName,Version,Vendor")] AppIndex appIndex)
        {
            if (ModelState.IsValid)
            {
                db.AppIndexes.Add(appIndex);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(appIndex);
        }

        // GET: AppIndexes/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AppIndex appIndex = await db.AppIndexes.FindAsync(id);
            if (appIndex == null)
            {
                return HttpNotFound();
            }
            return View(appIndex);
        }

        // POST: AppIndexes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,AppName,Version,Vendor")] AppIndex appIndex)
        {
            if (ModelState.IsValid)
            {
                db.Entry(appIndex).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(appIndex);
        }

        // GET: AppIndexes/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AppIndex appIndex = await db.AppIndexes.FindAsync(id);
            if (appIndex == null)
            {
                return HttpNotFound();
            }
            return View(appIndex);
        }

        // POST: AppIndexes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            AppIndex appIndex = await db.AppIndexes.FindAsync(id);
            db.AppIndexes.Remove(appIndex);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVCTut/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCTut.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "HAMS/NIAPS Prototype System.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Send Us a Note.";

            return View();
        }
    }
}

MVCTut/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVCTut/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    4297 Pacific Highway<br />
    San Diego, CA<br />
    <abbr title="Phone">P:</abbr>
    xxx.xxx.xxxx
</address>

<address>
    <strong>Afloat POC:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Ashore POC:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVCTut/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}




<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="false">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
        <div class="item active">
            <div style="height: 360px; background-color: gainsboro; text-align: center;">
                <p>&nbsp;</p>
                <span style="align-content: center">
                    <i class="icon-openshift" style="font-size:4em"></i>&nbsp;
                    <span style="font-size:52px" class="lead">HAMS/NIAPS 3.X</span>
                </span>
                <p class="lead">SSCPAC Replication and Monitoring System Prototype</p>
                <p><button type="button" class="btn btn-primary btn-lg" data-toggle="collapse" data-target="#demo1">Technology List &raquo;</button></p>
                <div id="demo1" class="collapse">
                    <div class="row">
                        <div class="col-md-4">
                            <ul>
                                <li>
                                    <span style="text-decoration:underline;"><i class="icon-angular-alt" style="font-size:22px"></i>Angular JS</span>
                                </li>
                                <li>
                                    <span style="text-decoration:underline;"><i class="icon-shell" style="font-size:22px"></i>Powershell</span>
                                </li>
                                <li>
                                    <span style="text-decoration:underline;"><i class="icon-backbone" style="font-size:22px"></i>MVC/Razor</span>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-4">
                            <ul>
                                <li>
                                    <span style="text-decoration:underline;"><i class="icon-csharp" style="font-size:22px"></i>Language</span>
                                </li>
                                <li>
                                    <span style="text-decoration:underline;"><i class="icon-javascript" style="font-size:22px"></i>Javascript</span>
                                </li>
                                <li>
                                    <span style="text-decoration:underline;"><i class="icon-html5" style="font-size:22px"></i>HTML 5</span>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-4">
                            <ul>
                                <li>
                                    <span style="text-decoration:underline;"><i class="icon-database-alt2" style="font-size:22px"></i>SQL Server</span>
                                </li>
                                <li>
                                    <span style="text-decoration:underline;"><i class="icon-unity" style="font-size:22px"></i>.NET Framework</span>
                                </li>
                                <li>
                                    <span style="text-decoration:underline;"><i class="icon-d3" style="font-size:22px"></i>LINQ/EF</span>
                                </li>
                            </ul>
                        </div>
                    </div>


                </div>
            </div>
        </div>

        <div class="item">
            <div style="height: 360px; background-color: gainsboro; text-align: center;">
               <p>&nbsp;</p>
                <span style="align-content: center">
                    <i class="icon-openshift" style="font-size:4em"></i>&nbsp;
                    <span style="font-size:52px" class="lead">HAMS/NIAPS 3.X</span>
                </span>
                <p class="lead">SSCPAC Replication and Monitoring System Prototype</p>
                <p><button type="button" class="btn btn-primary btn-lg" data-toggle="collapse" data-target="#demo2">Milestones &raquo;</button></p>
                <div id="demo2" class="collapse">
                    <div class="row">
                        <ul>
                            <li>
                                <span style="text-decoration:underline;">Database Schema Design</span>
                            </li>
                            <li>
                                <span style="text-decoration:underline;">Virtual Machines / SQL Server / MS Visual Studio</span>
                            </li>
                            <li>
                                <span style="text-decoration:underline;">IIS/Activity Directory (TBD)</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="item">
            <div style="height: 360px; background-color: gainsboro; text-align: center;">
                <p>&nbsp;</p>
                <span style="align-content: center">
                    <i class="icon-openshift" style="font-size:4em"></i>&nbsp;
                    <span style="font-size:52px" class="lead">HAMS/NIAPS 3.X</span>
                </span>
                <p class="lead">SSCPAC Replication and Monitoring System Prototype</p>
                <p><button type="button" class="btn btn-primary btn-lg" data-toggle="collapse" data-target="#demo3">Admin &raquo;</button></p>
                <div id="demo3" class="collapse">
                    <div class="row">
                        <div class="col-md-4">
                            @Html.ActionLink("Hull", "Index", "Hull")<br />
                            @Html.ActionLink("CM", "Index", "CM")
                        </div>
                        <div class="col-md-4">
                            @Html.ActionLink("AppIndexes Infos", "Index", "AppIndexes")<br />
                            @Html.ActionLink("PubIndexes", "Index", "PubIndexes")
                        </div>
                        <div class="col-md-4">
                            @Html.ActionLink("Amendment Infos", "Index", "AmendmentInfos")<br />
                            @Html.ActionLink("Servers", "Index", "Servers")
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @*<a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>*@


    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span>
    </a>
</div>



<div class="row">
    <div class="col-md-4"><span style="text-decoration:underline;"><i class="icon-docker" style="font-size:2em"></i><span style="font-size:32px" class="lead">Afloat Info</span></span>

        <p>
            Centralized Tracking of All Current Inventory and Configuration Management details on each ship.
        </p>
        <p><a class="btn btn-default" href="">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <span style="text-decoration:underline;"><i class="icon-alpinelinux" style="font-size:2em"></i><span style="font-size:32px" class="lead">Ashore Info</span></span>


        <p>Improves Advance Level of Automation and Replication Visibility.</p>
        <p><a class="btn btn-default" href="">Add New Application &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <span style="text-decoration:underline;"><i class="icon-codepen" style="font-size:2em"></i><span style="font-size:32px" class="lead">Dashboard</span></span>
        <p>View a Sample Dashboard View</p>
        <p><a class="btn btn-default" href="/Sample">Sample Dashboard &raquo;</a></p>
    </div>
</div>
@*<div class="row" style="background-color: darkgray; width: 100%;">
    <div class="col-md-6">
        <span style="color: white">hello</span>
    </div>
    <div class="col-md-6">
        <span style="color: white">hello</span>
    </div>
    
</div>*@